[workspace]
members = [
    "fluent-syntax",
    "fluent-bundle",
    "fluent-fallback",
    "fluent-io",
    "fluent-resmgr",
    "fluent-pseudo",
    "fluent-testing",
    "fluent",
    "intl-memoizer"
]

exclude = [
    "fluent-cli",
]
