[package]
name = "fluent-fallback"
description = """
High-level abstraction model for managing localization resources
and runtime localization lifecycle.
"""
version = "0.0.3"
edition = "2018"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]

[dependencies]
fluent-bundle = { version = "0.11", path = "../fluent-bundle" }
reiterate = "0.1.3"
async-std = "1.5"

[dev-dependencies]
elsa = "1.3.2"
unic-langid = { version = "0.8", features = ["macros"] }
fluent-langneg = "0.12"
