[package]
name = "fluent-fallback"
description = """
High-level abstraction model for managing localization resources
and runtime localization lifecycle.
"""
version = "0.1.0"
edition = "2018"
authors = [
    "Zibi Braniecki <gandalf@mozilla.com>",
    "Staś Małolepszy <stas@mozilla.com>"
]
homepage = "http://www.projectfluent.org"
license = "Apache-2.0/MIT"
repository = "https://github.com/projectfluent/fluent-rs"
readme = "README.md"
keywords = ["localization", "l10n", "i18n", "intl", "internationalization"]
categories = ["localization", "internationalization"]

[dependencies]
chunky-vec = "0.1"
fluent-bundle = { version = "0.14", path = "../fluent-bundle" }
futures = "0.3"
pin-cell = { git = "https://github.com/withoutboats/pin-cell", rev = "4d5803d83c6b3bffd62c9e73a0ceaf5ec6f01495" }
once_cell = "1.5"

[dev-dependencies]
fluent-langneg = "0.13"
unic-langid = { version = "0.9", features = ["macros"] }
fluent-testing = { git = "https://github.com/projectfluent/fluent-rs" }
fluent-resmgr = { path = "../fluent-resmgr" }
criterion = "0.3"

[[bench]]
name = "localization"
harness = false
